modLoader="javafml" 
loaderVersion="[41,)"
license="All rights reserved"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"
[[mods]] 
modId="pixelmonworld"
version="${file.jarVersion}"
displayName="Example Mod"
#updateJSONURL="https://change.me.example.invalid/updates.json" 
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" 
#logoFile="logo.png"
credits="Thanks for this example mod goes to Java"
authors="Love, Cheese and small house plants"
#displayTest="MATCH_VERSION" # MATCH_VERSION is the default if nothing is specified (#optional)

description='''
Lorem ipsum
'''
[[dependencies.pixelmonworld]] 
    modId="forge" 
    mandatory=true 
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.pixelmonworld]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
